DOMAIN = "presence_simulation"
SWITCH_PLATFORM = "switch"
SWITCH = "presence_simulation"
RESTORE_SCENE = "presence_simulation_scene"
SCENE_PLATFORM = "scene"
UNIQUE_ID = "presence_simulation_1747884960"
MY_EVENT = "presence_simulation_change"
